### ISSUE TITLE
erpnext 15

### ISSUE THREAD

**Issue by tahaalislb** [HUMENTH/Guide-to-Install-Frappe-ERPNext-in-Ubuntu-22.04-LTS#3]
what i need to modify so i can install erpnext 15 and do i need to install python3.11?

cause now when i finish the installation i can't reach the web using the local ip address of server and when i run "bench restart" an error occur?

**Comment by HUMENTH** [comment]
@tahaalislb 
> what i need to modify so i can install erpnext 15

Just replace version-14 to version-15 in all commands

> do i need to install python3.11?

It is not mandatory requirement; you can also install frappe/erpnext (version-15) with python3.10

> cause now when i finish the installation i can't reach the web using the local ip address of server and when i run "bench restart" an error occur?

You can access your local erpnext instance using <Local IP>:8000 or 127.0.0.1:8000 after "bench start".
"bench restart" only works in Production deployment.

please check branch [version-15](https://github.com/HUMENTH/Guide-to-Install-Frappe-ERPNext-in-Ubuntu-22.04-LTS/tree/version-15)
