### ISSUE TITLE
welcome email and forget password

### ISSUE THREAD

**Issue by tahaalislb** [HUMENTH/Guide-to-Install-Frappe-ERPNext-in-Ubuntu-22.04-LTS#4]
hi 
i have an issue after installing frappe and erpnext , how i can set email for the system so when i add new user it send an email to the user so he can configure his password or when the user want to forget his password an email sent to his email so he can configure his new password

**Comment by HUMENTH** [comment]
@tahaalislb https://docs.erpnext.com/docs/user/manual/en/email-account
